version: '3.9'

services:
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app_container
    volumes:
      - ./db.yaml:/app/db.yaml  # Mount the db.yaml file into the container
    networks:
      - django_app_net  # Use the custom network for the Python script

networks:
  django_app_net:
    external: true
